AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy one secure S3 bucket, with name sourced from SSM Parameter Store.

Parameters:
  BucketNameParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /my-app/bucket-name
    Description: SSM parameter that contains the globally unique S3 bucket name.

Resources:
  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketNameParameter
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

        

Outputs:
  BucketName:
    Description: Name of the deployed secure S3 bucket.
    Value:
      Ref: SecureBucket
